### ISSUE TITLE
US: Setup Cypress for Frontend Testing

### ISSUE THREAD

**Issue by patrickhladun** [patrickhladun/moodscape#31]
As a developer, 
I want to set up Cypress for frontend testing 
so that I can ensure the reliability and correctness of my frontend code through automated tests.

## Acceptance Criteria
- Cypress is installed and configured in the project environment.
- A `cypress` directory is created in the project to house all Cypress test files and configurations.
- A sample test file is created in the `cypress/integration` directory to verify the setup.
- The test runner is configured to automatically discover and run tests located in the `cypress/integration` directory.
- Documentation is added to the project README explaining how to run the tests using Cypress.

## Tasks
- [x] Install Cypress in the project environment.
- [x] Configure Cypress in the `cypress.json` file.
- [x] Create a `cypress` directory in the project.
- [x] Create a `cypress/integration` directory to store test files.
- [x] Write a sample test case in the `cypress/integration` directory to verify the setup.
- [x] Update project README with instructions for running tests using Cypress.
